### ISSUE TITLE
figure out how to get EC2 AMI listed under "Community AMIs"

### ISSUE THREAD

**Issue by paciorek** [ucberkeley/bce#22]
At present, one can find it and start an instance using the AMI by going to the EC2 dashboard and then clicking on AMIs tab on the left and then searching "BCE-spring-2015" under "Public Images".

But if one directly from the dashboard clicks on Launch, then at Step 1 of "Choose an AMI", BCE is not listed under the Ubuntu images under Community.

**Comment by ck37** [comment]
This seems to be resolved:

<img width="645" alt="screen shot 2015-07-23 at 9 14 31 am" src="https://cloud.githubusercontent.com/assets/50770/8855709/8119fe60-311b-11e5-9ba7-58675f1b9fa7.png">
