### ISSUE TITLE
installation of mosh has a problem

### ISSUE THREAD

**Issue by paciorek** [ucberkeley/bce#23]
Aaron asked for mosh and git-annex to be installed post-install (perhaps only on EC2?).

Installation via apt-get update gives this error (illustrating here with mosh)

Processing triggers for libc-bin (2.19-0ubuntu6.5) ...
Processing triggers for ufw (0.34~rc-0ubuntu2) ...

**\* Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@master.(none)')
E: Problem executing scripts DPkg::Post-Invoke 'if [ -x /usr/bin/etckeeper ]; then etckeeper post-install; fi'
E: Sub-process returned an error code

**Comment by aculich** [comment]
Looks like your post-install needs to configure git in the root account first before you do the apt-get which triggers [etckeeper](http://evilrouters.net/2011/02/18/using-etckeeper-with-git-on-ubuntu/)

Here's the bruteforce way to do it in your post-install:

``` bash
git config --global user.email "bce@lists.berkeley.edu"
git config --global user.name "BCE Release Team"
```

It's unfortunate that it doesn't automatically capture that common error and gracefully handle an unconfigured case like this.

**Comment by paciorek** [comment]
Ok, I added Aaron's lines to the post-install script, modify-for-aws.sh and things seem fine now.
