### ISSUE TITLE
Emacs key binding Ctrl+Space not working in xfce4

### ISSUE THREAD

**Issue by aculich** [ucberkeley/bce#25]
The default keybindings with xfce4 conflict with fundamental keyboard shortcuts in Emacs.

This is a known problem and has a straightforward solution.

We may want to consider documenting this in a BCE known problems list and/or just changing the default in the next BCE release since it is more likely to affect our community than a changed keybinding in the ibus system.

Details: http://lists.gnu.org/archive/html/help-gnu-emacs/2014-05/msg00282.html

```
I first opened IBus ($ ibus-setup) and there I changed Ctrl<space> into
Alt<space>. I hope it won't destroy anything, but at least C-<SPC> now sets
the mark in emacs.
```

**Comment by ryanlovett** [comment]
In current BCE dev builds, with emacs24 installed after provisioning, typing Control-space causes emacs to report "Mark set".

ibus-setup shows that the default keyboard shortcut is set to Super-space.
