### ISSUE TITLE
History is not (always) preserved between terminals

### ISSUE THREAD

**Issue by davclark** [ucberkeley/bce#27]
Have a currently running process, closed a terminal, history was empty. This is easy to reproduce with something like the following as a running process, and click the 'x' on the terminal window:

while [ 0 -lt 1 ] ; do echo 'o crap'; done

Any ideas?

**Comment by ryanlovett** [comment]
bash is usually configured to save history in one file which gets written
when the last bash instance exits. At the SCF we save history into
tty-specific files so they all get preserved. I can put that bit of bash
config into BCE.

Ryan

**Comment by davclark** [comment]
Rad!

**Comment by ryanlovett** [comment]
Commit 78f9f17 has bash save to ~/.bash_history.d/$n where $n is the number of the tty that bash is running in. It gets written when bash exits.
