### ISSUE TITLE
Summer 2015 release as EC2 AMI

### ISSUE THREAD

**Issue by ck37** [ucberkeley/bce#49]
Does the summer 2015 release exist as an EC2 AMI? I can only find the spring 2015 release :(

**Comment by paciorek** [comment]
I never got around to building it for summer 2015, partly just because I
didn't know that anyone was using the spring 2015 one other than me.  If we
think there is demand, I could do it (or tell you how to do it). Otherwise
I'll make sure to do it for fall 2015 release.

chris

**Comment by ck37** [comment]
Gotcha, yeah I would be happy to do it or otherwise help out.

**Comment by aculich** [comment]
It might be helpful to have the official BCE AMI for the AWS train the trainer session happening next week.

**Comment by paciorek** [comment]
I'm on vacation next week so will not be able to do a summer 2015 AMI.

I would think the AWS train the trainer could use the spring 2015 AMI, no?

If not, and if anyone wants to build the summer 2015 AMI I can help give
some tips before I leave on Sunday.

**Comment by aculich** [comment]
@paciorek any tips you have that may save us time re-learning what you've already figured out would be much appreciated.

**Comment by paciorek** [comment]
I looked back at my notes and don't have much recorded.

Basically, I believe this covers it:
- edit BCE-14.10-amd64.json file stanza for amazon-ebs type (update
  ami_name, and per Chris K's thought, perhaps swap 'region' and
  'ami_regions' contents so building happens in us-west-2
- following HOWTO.md in provisioning run "make ec2"
- (a bit vague here..) I believe this will upload the AMIs to us-west-{1,2}
  in the builders AWS account. So far this has been the SCF account. I'm
  happy to keep the AMIs there, but if someone else builds, we end up with
  the AMIs located in different places, which could be confusing.
- make sure to set the AMIs to be public -- go to AWS Management Console,
  EC2 dashboard, select AMIs, click on the AMI for BCE and then choose
  Actions->Modify Image Permissions. Select 'Public'.

I think that's it but possible I'm forgetting something.

**Comment by paciorek** [comment]
oh, and change the source AMI so that it is for the relevant version of
Ubuntu (now 15.04).

Current source AMI is in us-west-1 and is
ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-20140816

So we'd want to search Community AMIs for a recent hvm-ssd AMI for the
relevant Ubuntu version.

**Comment by ck37** [comment]
Yeah I was just noticing that the current dev code doesn't even build on EC2 right now due to using the old AMI - it hangs while waiting for SSH to be enabled.

The new AMIs are listed at https://cloud-images.ubuntu.com/releases/15.04/release/ so I'm testing the hvm-ssd one now.

**Comment by paciorek** [comment]
I just commited a change to dev branch that has updates to the
BCE-summer-2015.json to be for 15.04 and to build on us-west-2.

chris

**Comment by ck37** [comment]
Ok, I have created BCE-2015-summer AMIs on us-west-2 (ami-1f121e2f) and us-west-1 (ami-859469c1)  with the latest source code and made them public. These are hosted on the D-Lab AWS account. Closing this issue.
