### ISSUE TITLE
Beautiful soup 3.2.1 fails to build

### ISSUE THREAD

**Issue by ck37** [ucberkeley/bce#5]
Is anyone else getting this error with Beautiful Soup failing? I luckily noticed the error message during the build and thought I'd note it since everything else seems to have worked.

---

```
virtualbox-iso: Downloading BeautifulSoup-3.2.1.tar.gz
virtualbox-iso: Traceback (most recent call last):
virtualbox-iso: File "<string>", line 20, in <module
virtualbox-iso: Complete output from command python setup.py egg_info:
virtualbox-iso: Traceback (most recent call last):
virtualbox-iso:
virtualbox-iso: File "<string>", line 20, in <module
virtualbox-iso:
virtualbox-iso: ----------------------------------------
virtualbox-iso:     Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-delbg1u1/BeautifulSoup
```

**Comment by ryanlovett** [comment]
Yes, http://www.mail-archive.com/bce@lists.berkeley.edu/msg00049.html. How strict of a requirement is BeautifulSoup for you?

Thanks for the build feedback!

**Comment by ck37** [comment]
No worries on my end, I am not personally using BeautifulSoup right now; I'd think that bs4 would be fine too.

**Comment by davclark** [comment]
This is obsolete given the switch to anaconda.
