### ISSUE TITLE
summer-2015 EC2 image lacking python packages

### ISSUE THREAD

**Issue by paciorek** [ucberkeley/bce#64]
@ck37: do you have any log files from when you built BCE-summer-2015 for EC2? 
I noticed that all (or at least the ones I checked) of the Python pkgs listed in py.txt and py3.txt were not actually installed. 

@aculich: for the moment, we may want to direct the D-Lab cloud working group to use BCE-spring-2015 if we don't rebuild summer-2015.

**Comment by paciorek** [comment]
@ck37:  I think we should remove the BCE-summer-2015 EC2 image. In looking at the packer build log you sent me, in addition to the missing Python packages, ipython itself is missing, and there are some issues with the R packages used in the Jupyter R kernel as well.  Given we are so close to doing fall-2015 I don't think spending time rebuilding summer-2015 makes sense.

I can work with @ryanlovett  for BCE-fall-2015 to make sure the EC2-related errors in the provisioning are resolved.

Thoughts?

**Comment by paciorek** [comment]
Actually it looks like the Python pkgs are being put in /home/oski/miniconda, so they are accessible to the oski user but not the ubuntu user.  That said, I still think it best to remove the summer EC2 and start over with fall-2015.

**Comment by ck37** [comment]
Sounds fair to me - I've changed the AMI to be private.

**Comment by paciorek** [comment]
Thanks.
