### ISSUE TITLE
BCE HackDay

### ISSUE THREAD

**Issue by aculich** [ucberkeley/bce#65]
After various discussions I've had with @davclark , @paciorek , @ck37 , and @ryanlovett , I wonder if it's time to have a BCE HackDay ahead of doing a Fall release? Is there a day (or half day or even just 2 hours) that we could get together in the next couple of weeks? Preferably before the Oct 15th Cloud WG topic which is: BCE on AWS?

Maybe Friday 10/2 or Friday 10/9?

I'll start triaging all the [issues we have here](https://github.com/ucberkeley/bce/issues) and in the [documentation issues](https://github.com/ucberkeley/bce/issues) ahead of that HackDay.

I'd like to address issues like this one that Dav and I discussed on the [uc-juptyer slack](https://uc-jupyter.slack.com/messages/general/):

aculich [6:49 PM] 
@davlab Is anaconda the approach used in http://bce.berkeley.edu ?

aculich [6:49 PM]
Whatever the approach, I wonder if we ought to include a short description in the https://github.com/ucberkeley/bce/blob/dev/README.md  of the high-level decisions and reasons for making them so that:

aculich [6:49 PM]
- folks can (without looking at the build scripts) see what our approach is; and

aculich [6:49 PM]
- can see our rationale (which won’t necessarily be obvious when looking at the build scripts)
  NEW MESSAGES

----- Yesterday September 20th, 2015 -----

davlab [7:42 PM] 
@aculich: yes, we use anaconda now. We aren’t using it as well as we could (i.e., I’d like to enable `conda install bce=fall-2015` for at least arbitrary-ish unix). Such a thing is not hard, we just haven’t gotten to it.

davlab [7:43 PM]
I think a great first step would be simply documenting the choices we made even without the rationale! I’ve been meaning to do this, and I think we should explain how to install most of the major tools - like PyCharm, RStudio, anaconda, etc.

**Comment by paciorek** [comment]
Sounds like a good idea to me. 10/2 and 10/9 both work though I teach
2-3:30.

**Comment by ck37** [comment]
That would be fun - I’m open 12:30-3pm on 10/2 and 10/9.

**Comment by ryanlovett** [comment]
Hi all,

Yes, I'm available. And I apologize again for the delay. I created a test
build for fall on Saturday and need to clean up some of the FAILs.

If 10/15 is the target date, would you be against basing Fall on Ubuntu
15.10 which comes out on 10/22? Would it be okay for the 10/15 event to be
based on a Fall preview based on 15.10 beta?

Ryan

**Comment by aculich** [comment]
@ryanlovett making it a preview release based on Wily Warewolf (15.10) would be good-- the working group can help with some of preview-release testing for the final fall release!

**Comment by paciorek** [comment]
I'm wary of basing on a release of Ubuntu that is not yet out. Is there a
compelling reason to wait as opposed to just using 15.04?

**Comment by davclark** [comment]
I'm mostly interested in getting BCE onto an LTS release, and keeping it that way. I've run into annoying issues surrounding things like CUDA.
