### ISSUE TITLE
change default Vbox user to be ubuntu

### ISSUE THREAD

**Issue by paciorek** [ucberkeley/bce#69]
@aculich  and I had a discussion just now that it is nice to have the same user name in VBox and EC2. @ryanlovett  and I had a separate discussion in which Ryan was happy to have ubuntu be the default user.

@ryanlovett , please make ubuntu be BCE_USER for VBox in fall-2015.

**Comment by davclark** [comment]
At one point, I'd had oski also set up as the EC2 user (maybe you just didn't notice?). But, while it saddens me, I'm OK to go with a more practical choice.

**Comment by paciorek** [comment]
yeah, we were using oski on EC2 and definitely noticed, but since you need
to first SSH to ubuntu, it's a hassle to have our primary user be different.

**Comment by ryanlovett** [comment]
Fixed by commit 416e6668a2c03fe4f84890d8f606ab102c3237b6.
