### ISSUE TITLE
remove old BCE AMIs

### ISSUE THREAD

**Issue by paciorek** [ucberkeley/bce#71]
I'm revisiting this issue of removing old BCE EC2 AMIs that we discussed by email in spring 2015.  The current public BCE AMIs are BCE-2015-spring and the pending BCE-2015-fall plus BCE-0.1.3 and BCE-0.1.2.  We'd like to remove the BCE-0.1-{2,3} (or at least not have them be public).

Dav, are BCE-0.1.3 and BCE-0.1.2 (account *****67033) hosted on one of your accounts?

If so, can you remove them or make them private?

chris

**Comment by davclark** [comment]
These were actually under my "personal" davclark@berkeley.edu account. Took me a while to track them down. I deregistered all of them, and they appear to be gone!
