### ISSUE TITLE
Reorganize BCE files on shared folders

### ISSUE THREAD

**Issue by davclark** [ucberkeley/bce#72]
Right now we have lightweight files that make sense to sync (BCE slides) in with archives of VMs going back to 0.1. Can we move all large assets to Box, and delete them from google drive? I'm also fine to move everything to Box.

(I opened this 26 days ago, but put it in the wrong repo!)

**Comment by davclark** [comment]
If folks agree, I can actually move files around.

**Comment by paciorek** [comment]
can you clarify what archives of VMs you mean and where they are?  I see
only ~3-4 Mb of stuff in the bce git repo.

**Comment by davclark** [comment]
Google drive: https://drive.google.com/a/berkeley.edu/folderview?id=0B2JP4TBQGyuXZGo4MzNYcTdzU0U&usp=sharing

I can't sync the "BCE" folder because it's many jigabytes.

**Comment by davclark** [comment]
I'll give this one more week. If no-one chimes in, I'll delete the files that lower my productivity.

**Comment by ryanlovett** [comment]
I'm not against your solution, but would it be easier to just [selectively sync](https://support.google.com/drive/answer/2375083) to/from Drive?

**Comment by davclark** [comment]
That only supports top-level folders in Drive, so that doesn't work in this case. If I'm wrong, please enlighten me! It would really be great for the mess I'm constantly dealing with on GDrive.

**Comment by davclark** [comment]
Seems like no-one is against this solution. I removed it from the BCE folder, but the images should still be avilable in pre-existing collaborators shared folders...
