### ISSUE TITLE
Add PyCharm to Gnome Apps menu

### ISSUE THREAD

**Issue by ck37** [ucberkeley/bce#9]
Would it be possible to add PyCharm to the Gnome Applications menu? I believe it will be used pretty often in the DLab python trainings, and it seems like it would be a good usability improvement to not require typing "pycharm<tab>" on a terminal to run it.

Alternatively, a desktop icon could be the second best option.

**Comment by ryanlovett** [comment]
Fixed, thanks!

**Comment by ryanlovett** [comment]
Chris, when launching pycharm.sh from the manually created launcher, it prompts the user to create a script in /usr/local/bin and to create another desktop launcher. If the user accepts these default choices, it asks the user for the oski password and completes the installation. The latter requires that the user knows the password ("oski") but this is inconvenient.

These actions are contained within the PyCharm jar files so are not easily modified.

I have renamed the desktop launcher to PyCharm Installation to disambiguate it from the application. A future release should find a way to make the installation completely unattended.
